### ISSUE TITLE
Any roadmap to Cucumber 4 compatibiity?

### ISSUE THREAD

**Issue by oche-jay** [MicroFocus/octane-cucumber-jvm#1]
ALM Octane looks promising, however, a lack of compatibility with Cucumber 4 means many new projects will not be able to use it.

**Comment by yuval-koren** [comment]
Thank you for your comment.
We are aware of this issue and are working on Cucumber 4.2 support. It is on our near future roadmap.

**Comment by oche-jay** [comment]
Thanks for coming back to me, when you say near future, do you have an estimate. - next few weeks, a couple of months or next year.

**Comment by yuval-koren** [comment]
Hi oche-jay,
A lot of customers are asking for that support. 
We are actively working now on it.
It's hard to say exactly when it we will finished.
Hopefully, by next month or the month after it...
If you wish, we can give you early access to our beta when it is available.

**Comment by oche-jay** [comment]
Thanks yuval-koren, yes I would very much like the beta access

**Comment by sharonvardi** [comment]
@oche-jay The Cucumber 4 support is released. To use it you can follow the instruction in the README.md
