### ISSUE TITLE
Add cucumber 6.X compatibility

### ISSUE THREAD

**Issue by picpicpic** [MicroFocus/octane-cucumber-jvm#11]
Hello,

Cucumber is currently in version **6.X**
octane-cucumber-jvm is using cucumber **4.X** which is quite old and not compatible with version 6.X

Do you have a plan to update dependencies of the plugin or any solution to work with recent version of cucumber ?

Thx and regards
Aldric

**Comment by micheleh** [comment]
Hello,

Yes, supporting Cucumber 5.x and 6.x is on our backlog for the near future.

Best regards,
Ehud

**Comment by ArnaudCharpentier** [comment]
Hi @micheleh ,
Do you have an approximate release date for this feature?
Regards

Arnaud

**Comment by micheleh** [comment]
Hi @ArnaudCharpentier 
This is still in the early stages so I cannot commit to a release date. However, I can assure you that it has the top priority.
Regards,
Ehud

**Comment by haldenjesper** [comment]
@micheleh 
Is this included in 15.1.90 released today? We need this ASAP....
PS this is a continuous requirement:)
br jesper

**Comment by micheleh** [comment]
@haldenjesper 
Unfortunately, not yet. It has top priority and we're doing our best to provide it to the customers.
Please note that Octane Cucumber JVM is a Cucumber plugin and as such is not bound to a specific Octane release. Practically it means that when released, it can be used with your current Octane version.
Ehud

**Comment by haldenjesper** [comment]
@micheleh so what can we tell our users?

br jesper

**Comment by micheleh** [comment]
@haldenjesper I suggest asking your contact at Micro Focus for a formal answer

**Comment by picpicpic** [comment]
Hi @micheleh

Do you have any new about this topic ? 

Thx and regards

**Comment by micheleh** [comment]
Hi @picpicpic 

I have good news 😀

R&D is launching a new tool that replaces the cucumber-jvm-plugin and supports more versions of Cucumber (including v 6.x) as well as more BDD Frameworks such as cucumber-js, php-behat, python-radish, python-behave, and cucumber-ruby. 
The new tool can be called directly from your CI system either as an executable jar or as a maven plugin. This means that your test code will not require the dependency in octane-cucumber-jvm anymore 😁
Note that uploading the maven plugin to the maven repository is still in the works and is expected to be completed in the coming days.
You can find the new tool on GitHub: [bdd2octane](https://github.com/MicroFocus/bdd2octane/tree/1.0.0)

Ehud

**Comment by micheleh** [comment]
@picpicpic you may now find the new tool also on the Maven Repository:
[Bdd2octane](https://mvnrepository.com/artifact/com.microfocus.adm.almoctane.bdd/bdd2octane)

**Comment by picpicpic** [comment]
@micheleh Thx! I will check the new tool and try to integrate it :+1: 

Have a nice day!

**Comment by AlexBravo95** [comment]
Hi 6.7.0 version cucumber and above does not work,

**Comment by AlexBravo95** [comment]
Hello, some update for cucumber 7

**Comment by micheleh** [comment]
@AlexBravo95 we have a new tool to support different BDD frameworks including Cucumber 7. This tool is supported by ALM Octane v16.0.200 and later.
Look at [Bdd2octane](https://mvnrepository.com/artifact/com.microfocus.adm.almoctane.bdd/bdd2octane) for details
Also, look at [Inject BDD test results to ALM Octane](https://admhelp.microfocus.com/octane/en/16.0.100-16.0.400/Online/Content/UserGuide/how-create-tests-bdd.htm#mt-item-3)
And you can find the GitHub repository here: [bdd2octane](https://github.com/MicroFocus/bdd2octane)

**Comment by micheleh** [comment]
> @AlexBravo95 we have a new tool to support different BDD frameworks including Cucumber 7. This tool is supported by ALM Octane v16.0.200 and later. Look at [Bdd2octane](https://mvnrepository.com/artifact/com.microfocus.adm.almoctane.bdd/bdd2octane) for details Also, look at [Inject BDD test results to ALM Octane](https://admhelp.microfocus.com/octane/en/16.0.100-16.0.400/Online/Content/UserGuide/how-create-tests-bdd.htm#mt-item-3) And you can find the GitHub repository here: [bdd2octane](https://github.com/MicroFocus/bdd2octane)
