### ISSUE TITLE
NodeJS Octane-Cucumber

### ISSUE THREAD

**Issue by macroking** [MicroFocus/octane-cucumber-jvm#2]
Do you have Octane-Cucumber NodeJS module?

**Comment by macroking** [comment]
Can I submit a PR for NodeJS Octane-Cucumber npm module?

**Comment by yuval-koren** [comment]
Hi macroking,
We are currently working on supporting latest Cucumber library (4.2).
Lots of work as they had a lot of changes...

It will be great if you can submit a PR. 
After we finish the our work, we can merge your PR and publish to npm.
