### ISSUE TITLE
Do you have Octane-Cucumber gem for Ruby?

### ISSUE THREAD

**Issue by raamojirao** [MicroFocus/octane-cucumber-jvm#4]
Out test automation framework is built using Ruby and Cucumber. I would not be able to use Octane-Cucumber-jvm in our test automation framework as ours is written using Ruby. 

When I push the results to ALM Octane using XML files generated by Cucumber then each scenario is pushed as separate test case. In our framework each automated test case will have multiple scenarios and each scenario is pushed as a separate test case which isn't right. I was suggested to use octane-cucumber-jvm in our automation framework and NOT cucumber. I do not see Ruby version of octane-cucumber. Please help!!

**Comment by sharonvardi** [comment]
Hi @raamojirao. Octane Cucumber for Ruby is in our backlog, but with no ETA yet.
For more details you contact us directly via support or post on Idea Exchange.
