### ISSUE TITLE
Parallel execution using octane-cucumber-jvm

### ISSUE THREAD

**Issue by kalbongpalautot** [MicroFocus/octane-cucumber-jvm#7]
Hi team, not sure if this is the right place to ask this question or put this but my apologies if not. Anyways, we are using Octane and using this plugin so we can publish the test results back to Octane when we run our test as part of CI/CD. We want to leverage the parallel execution provided by the latest cucumber version but could not get it working using this plugin. I am pretty sure we might just be missing something. We are using Maven and just wondering if you have a sample pom.xml or configuration we can refer to to guide us will be great.

Many thanks in advance.

**Comment by kalbongpalautot** [comment]
We are using maven-failsafe-plugin to execute our tests and set the plugin configuration as per below and configured single runner:

**POM:**
            

> <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
                <executions>
                    <execution>
                        <configuration>
                            <useUnlimitedThreads>true</useUnlimitedThreads>
                            <parallel>method</parallel>
                            <threadCount>4</threadCount>
                            <testFailureIgnore>true</testFailureIgnore>
                            <includes>
                                <include>**/OctaneRunnerTest.java</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            

> </plugin>

**Runner:**

package <"name space">;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(plugin = { "com.hpe.alm.octane.OctaneGherkinFormatter:gherkin-results\\OctaneRunnerTest_OctaneGherkinResults.xml",
    "json:target/cucumber.json" },
    features = "path to feature files",
    glue = "path to step def classes"
)

public class OctaneRunnerTest {

}

**Comment by micheleh** [comment]
Hi

What version of Cucumber are you using? Note that this plugin supports Cucumber v4.8.1 but not v5.x.x

You say 
> ... but could not get it working using this plugin

Could you please elaborate on that statement?

**Comment by kalbongpalautot** [comment]
> Hi
> 
> What version of Cucumber are you using? Note that this plugin supports Cucumber v4.8.1 but not v5.x.x
> 
> You say
> 
> > ... but could not get it working using this plugin
> 
> Could you please elaborate on that statement?

Hi there, thanks for getting back to me. We are using below octane-cucumber-jvm plugin version, configured the maven-failsafe-plugin as per the original post and also created a runner 'OctaneRunnerTest ' and set the CucumberOptions values accordingly as per above too. 

As for your question what cucumber version, I am not entirely sure what cucumber version the 'octane-cucumber-plugin' version '**15.1.0**' or do we have to add a specific cucumber version in the maven dependency too? Honestly what help we need is a sample maven (pom.xml) configuration to help use guide how to configure our project maven pom.xml.

Hope that clarifies and thanks in advance. 

> <dependencies>

	<dependency>
				<groupId>com.hpe.alm.octane</groupId>
				<artifactId>**octane-cucumber-jvm**</artifactId>
				<version>**15.1.0**</version>
	 </dependency>
<dependencies>

>

**Comment by micheleh** [comment]
Try this
```
    <dependencies>
            <dependency>
            <groupId>com.hpe.alm.octane</groupId>
            <artifactId>octane-cucumber-jvm</artifactId>
            <version>15.1.0</version>
        </dependency>
    </dependencies>
```

**Comment by kalbongpalautot** [comment]
Hi there again, that's exactly the dependency we are using right now (see above reply). Just a couple of questions if we dont have a sample or documentation how to connfigure the maven surefire plugin and the Octane Runner class:
1. do we need to add the cucumber-jvm too in the pom.xml dependencies section if we are already using the 'octane-cucumber-jvm'?
2. also, should we be using maven fail-safe plugin or just the maven surefire plugin to run the tests via maven?
3. we are using another cucumer maven reporting plugin on top of octane plugin and requires a *.json report input file. How can we configure the Octane Runner class to also generate a report file in json format?

I may be asking too much but if you have a sample pom.xml we can refer too where you use the 'octane-cucumber-jvm' to run tests in parallel and publish results back to octane will be great. 

Thanks in advance. Cheers.

**Comment by sharonvardi** [comment]
Hi @kalbongpalautot,

I will try to answer your questions one by one.
1. cucmber-jvm is included in octane-cucumber-jvm and you don't need to add it to your dependencies.
2. You can use either, as you can see in [Cucumber Parallel Execution documentation](https://cucumber.io/docs/guides/parallel-execution/)
3. You can configure multiple plugins in `CucumberOptions`. Please consult Cucumber documentation.

Example POM file. (in comment - surefire example)
```    
    <dependencies>
        <dependency>
            <groupId>com.hpe.alm.octane</groupId>
            <artifactId>octane-cucumber-jvm</artifactId>
            <version>15.1.0</version>
        </dependency>
    </dependencies>


    <build>
        <plugins>
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-surefire-plugin</artifactId>-->
<!--                <version>2.22.0</version>-->
<!--                <configuration>-->
<!--                    <parallel>methods</parallel>-->
<!--                    <useUnlimitedThreads>true</useUnlimitedThreads>-->
<!--                </configuration>-->
<!--            </plugin>-->

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <parallel>methods</parallel>
                            <useUnlimitedThreads>true</useUnlimitedThreads>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

Example runner class:
```
package parallel;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(plugin = "com.hpe.alm.octane.OctaneGherkinFormatter:gherkin-results\\RunCucumberTest_OctaneGherkinResults.xml")
public class RunCucumberTest {
}
```

This is a working example I tried myself, taken from Cucumber documentation. If you encounter any more issues with Cucumber parallelism or failsafe plugins please consult relevant documentation.

**Comment by kalbongpalautot** [comment]
> Hi @kalbongpalautot,
> 
> I will try to answer your questions one by one.
> 
> 1. cucmber-jvm is included in octane-cucumber-jvm and you don't need to add it to your dependencies.
> 2. You can use either, as you can see in [Cucumber Parallel Execution documentation](https://cucumber.io/docs/guides/parallel-execution/)
> 3. You can configure multiple plugins in `CucumberOptions`. Please consult Cucumber documentation.
> 
> Example POM file. (in comment - surefire example)
> 
> ```
>     <dependencies>
>         <dependency>
>             <groupId>com.hpe.alm.octane</groupId>
>             <artifactId>octane-cucumber-jvm</artifactId>
>             <version>15.1.0</version>
>         </dependency>
>     </dependencies>
> 
> 
>     <build>
>         <plugins>
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-failsafe-plugin</artifactId>
>                 <version>2.22.0</version>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>integration-test</goal>
>                             <goal>verify</goal>
>                         </goals>
>                         <configuration>
>                             <parallel>methods</parallel>
>                             <useUnlimitedThreads>true</useUnlimitedThreads>
>                         </configuration>
>                     </execution>
>                 </executions>
>             </plugin>
>         </plugins>
>     </build>
> ```
> 
> Example runner class:
> 
> ```
> package parallel;
> 
> import io.cucumber.junit.Cucumber;
> import io.cucumber.junit.CucumberOptions;
> import org.junit.runner.RunWith;
> 
> @RunWith(Cucumber.class)
> @CucumberOptions(plugin = "com.hpe.alm.octane.OctaneGherkinFormatter:gherkin-results\\RunCucumberTest_OctaneGherkinResults.xml")
> public class RunCucumberTest {
> }
> ```
> 
> This is a working example I tried myself, taken from Cucumber documentation. If you encounter any more issues with Cucumber parallelism or failsafe plugins please consult relevant documentation.

Hi there, thanks for your inputs. We have actually tried that same setup and could not get the test to execute in parallel. Not sure how exactly you've tried it but we have thread to show the threadId generated in the @BEFORE annotation and we don't see multiple thread get generated. Maybe we are missing something. Anyways, will keep digging and exploring. Thanks again.
